# Generated by Django 6.0 on 2026-02-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_low_stock_threshold'),
        ('sales', '0002_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='products.product'),
        ),
    ]
