# Generated by Django 6.0 on 2026-02-19 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrtoken',
            name='expires_at',
        ),
    ]
