# Generated by Django 6.0 on 2026-01-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='shop_profiles/'),
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
