# Generated by Django 6.0 on 2026-02-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shop_profile_pic_delete_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='upi_id',
            field=models.CharField(default='example@upi', help_text='Your UPI ID (e.g., rahul@oksbi)', max_length=50),
        ),
    ]
