# Generated by Django 6.0 on 2026-02-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_shop_upi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='upi_id',
            field=models.CharField(blank=True, default='', help_text='Your UPI ID (e.g., rahul@oksbi)', max_length=50),
        ),
    ]
